### ISSUE TITLE
Support for `PravegaCluster` resource status

### ISSUE THREAD

**Issue by maddisondavid** [pravega/pravega-operator#10]
Report the high-level status / conditions via the status section of the custom resource.  A key scenario is to enable Helm to `--wait` on the deployment of the cluster.

Ideally the status would accurately indicate whether Pravega is ready to create streams.   Note that the Pravega controller startup routine involves more than exposing a TCP endpoint; some system streams are created before Pravega is truly ready.   Could the true readiness be detected somehow?

The solution will involve adding a `status` section to the CRD, and using the `UpdateStatus` method.

Note that the `status` section is expected to have some well-known elements, e.g. `conditions`.  The word _conditions_ has a meaning like "weather conditions" not "conditional logic".  There is a mindful design underlying this ([example](https://kubernetes.io/docs/concepts/architecture/#condition)).

**Comment by Tristan1900** [comment]
For the true readiness part, I talked to Shivesh and he told me that if the controller has exposed the grpc/rest port and if we can get OK response from those, we can assume the service is ready.

**Comment by adrianmo** [comment]
@Tristan1900, for reporting the status of the `PravegaCluster` resource, we should convey to the [Kubernetes API conventions](https://github.com/kubernetes/community/blob/master/contributors/devel/api-conventions.md#typical-status-properties). As a reference, we can take a look at etcd-operator's implementation, which is already complying with the convention. Please have a look at their [`status.go`](https://github.com/coreos/etcd-operator/blob/master/pkg/apis/etcd/v1beta2/status.go) and [documentation](https://github.com/coreos/etcd-operator/blob/master/doc/user/conditions_and_events.md).

In our case, we can also have three phases:
```
ClusterPhaseCreating              = "Creating"
ClusterPhaseRunning               = "Running"
ClusterPhaseFailed                = "Failed"
```

And at least a couple of conditions:

```
ClusterConditionReady             = "Ready"
ClusterConditionScaling           = "Scaling"
```

**Comment by adrianmo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Operator: Provide CR status information](https://trello.com/c/cVwUz0nj/111-operator-provide-cr-status-information)
