### ISSUE TITLE
Pravega config parameters are not getting updated dynamically using the command "kubectl edit"

### ISSUE THREAD

**Issue by mejodev1** [pravega/pravega-operator#111]
Pravega config parameters are not getting updated dynamically using the command `kubectl edit PravegaCluster <Clustername> -n <namespace>`

I edited `AUTHORIZATION_ENABLED` to false from true, but still it is not getting reflected in pravega controller.
```    
options:
      AUTHORIZATION_ENABLED: "false"
```
```
[root@worker1]# kubectl exec -it pravega-controller-56c6dc6699-lfs46 -n <namespace> -- /bin/sh
/opt/pravega #
/opt/pravega # echo $AUTHORIZATION_ENABLED
true
/opt/pravega # 
```

**Comment by adrianmo** [comment]
This is not supported in Pravega. Options are set at creation time and they can't be changed afterwards. I'm closing this issue.
