### ISSUE TITLE
Define appropriate Storage Classes for Pravega deployment services

### ISSUE THREAD

**Issue by RaulGracia** [pravega/pravega-operator#118]
**Problem description**
Currently, we use default Storage Classes to create persistent volumes for services deployed via the operator (i.e., Bookkeeper, Zookeeper). However, setting the appropriate parameters to the storage volumes based on the needs of services may be important both in terms of performance and storage efficiency. We need to find the right Storage Classes to cope with the performance and reliability needs of a Pravega deployment.

**Problem location**
Storage volume definition.

**Suggestions for an improvement**
Find appropriate Storage Classes for each service.

**Comment by pbelgundi** [comment]
Pravega does not use any persistent volumes now (since version operator 0.5.0 and pravega version 0.7)
@RaulGracia is this issue still relevant to Pravega Operator?

**Comment by RaulGracia** [comment]
Actually, this was related to the exploration of storage policies in vSan. But the point is that the operator enables to set any storage class of different volumes, which is what is supposed to do. We can close this issue.
