### ISSUE TITLE
Support for `PravegaStandalone` CRD

### ISSUE THREAD

**Issue by EronWright** [pravega/pravega-operator#125]
To support app-developer scenarios where a minimal Pravega footprint is desireable, it should be possible to deploy the "standalone" variant of Pravega.

Please don't attempt to overload the `PravegaCluster` resource for this purpose.    A cleaner approach would be to introduce a `PravegaStandalone` resource, with a fit-to-purpose spec.

**Comment by pbelgundi** [comment]
Should perhaps be needed for auto scaling...

**Comment by Ranganaths8** [comment]
Eron - please help us understand why we need this changes on operator side. thank you.

**Comment by Prabhaker24** [comment]
Closing this issue as @EronWright has not responded back.
