### ISSUE TITLE
Doc: Good to have a section for specifying image name and tag name to be used for Zookeeper Operator 

### ISSUE THREAD

**Issue by SomeshJoshi19** [pravega/pravega-operator#148]
**Problem description**
New Pravega users not aware of changing the default image name and tag name to `pravega/zookeeper-operator:<latest-release-tag>` in the `deploy/all_ns/operator.yaml` file while deploying `Zookeeper Operator`.

**Problem location**
Pravega Operator `README.md` file

**Comment by adrianmo** [comment]
@Aparnarr this issue needs to be reported in the zookeeper-operator repository, not here.
