### ISSUE TITLE
Update ConfigMap when upgrading to a different version

### ISSUE THREAD

**Issue by adrianmo** [pravega/pravega-operator#154]
When the `version` field is updated, a rolling upgrade is triggered and pods with the updated version start to replace the old ones. The new pods use an updated pod template, recreated by the operator during the upgrade process. That new pod template can contain changes not only to the image and tag to use, but also to the readiness probe, exposed ports, volumes, annotations, etc. However, the `ConfigMap` objects are not updated and are reused from one version to another.

This poses a problem because different versions of Pravega and BookKeeper may require different configuration to be set. For example, Pravega 0.3.2 uses a JVM version that does not support the `-XX:+UseCGroupMemoryLimitForHeap` option, but Pravega >= 0.4 does and it's recommended to make proper use of container resources.

Therefore, the `ConfigMap` for Controller, Segmentstore, and BookKeeper has to be updated ,or recreated, and used by the new pods.

**Comment by pbelgundi** [comment]
I see the need to upgrade the config map when upgrading from a Pravega version older than 0.3.2 but in other cases it may be unnecessary to create a new config map.
