### ISSUE TITLE
Make Pod affinity configurable

### ISSUE THREAD

**Issue by adrianmo** [pravega/pravega-operator#155]
At this moment, Pod affinity is configured as a soft requirement ([`PreferredDuringSchedulingIgnoredDuringExecution`](https://github.com/pravega/pravega-operator/blob/master/pkg/util/k8sutil.go#L53)) that tells the schedule to try placing pods of the same kind to different hosts. This configuration might be suitable for some environments and use cases, but it might not be optimal for others.

We should expose the affinity rules to be applied to BK, SS, and CC to allow users to customize and optimize pod scheduling for their use case and environment.

**Comment by Prabhaker24** [comment]
Closing this issue as we have an issue already for the same thing link to it https://github.com/pravega/pravega-operator/issues/364.
