### ISSUE TITLE
Define a manual recovery procedure for a failed upgrade

### ISSUE THREAD

**Issue by adrianmo** [pravega/pravega-operator#157]
An upgrade might face issue during the process, e.g., due to an invalid image/tag, incorrect configuration, a bug in a component, etc. When an error occurs during the upgrade of a Pravega component, the upgrade process stops. We should define a procedure to manually recover a Pravega cluster from that error state.

**Comment by pbelgundi** [comment]
Currently manual rollback by try to "upgrade" from the newer version to older version does not work as webhook prevents upgrade from a higher version to a lower version.
Here is the error message displayed:
```
pbelgundi@ubuntu:~$ k edit pravegacluster pravega
error: pravegaclusters.pravega.pravega.io "pravega" could not be patched: Internal error occurred: admission webhook "pravegawebhook.pravega.io" denied the request: unsupported upgrade from version 0.6.0-2239.6e24df7 to 0.5.0-2284.8c6c176
You can run `kubectl replace -f /tmp/kubectl-edit-4wuch.yaml` to try this update again.
```

**Comment by pbelgundi** [comment]
Since automated Rollback is implemented this should not be needed.
