### ISSUE TITLE
Add OpenAPI Schema Validation

### ISSUE THREAD

**Issue by maddisondavid** [pravega/pravega-operator#17]
Add a validation section to the CRD definition to validate the Custom Resources

**References:**
- https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#validation
- https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#schemaObject

**Comment by adrianmo** [comment]
The validation feature is available as beta in Kubernetes 1.12.

**Comment by pbelgundi** [comment]
Basic OpenAPIV3Schema Validation is added by PR: https://github.com/pravega/pravega-operator/pull/353
