### ISSUE TITLE
"Upgrade history" feature to be implemented

### ISSUE THREAD

**Issue by deenav** [pravega/pravega-operator#194]
**With current verison `0.4.0-rc1` of Pravega upgrade process, there is no way to find the `upgrade history` or `upgrade path` other than searching it from logs.** 

Only during the upgrade there are status like `Current Version` and `Target Version`  shown from `kubectl describe PravegaCluster` output. 

But after upgrade completion `kubectl describe PravegaCluster` only shows `Version` field, with that we can not determine the Previous Version from where the Pravega got upgraded.

And over the period of time if a customer/user performs multiple upgrades of Pravega then there should be a way to keep track of it. 

**So, it would be good to have some command readily available to check the previous version or upgrade path.**

**Comment by Tristan1900** [comment]
This probably could be done by keeping history in Pravega manifest `annotation` field. K8s uses the same way to keep track of the rollout history of deployment. [Ref](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#checking-rollout-history-of-a-deployment).
