### ISSUE TITLE
With "0.4.0" release, "0.3.2" pravega-operator gets installed using "helm install" method.

### ISSUE THREAD

**Issue by deenav** [pravega/pravega-operator#200]
With "0.4.0" release, "0.3.2" pravega-operator gets installed using "helm install" method `$ helm install charts/pravega-operator --name foo`

```
# helm ls --all
NAME            REVISION        UPDATED                         STATUS          CHART                           APP VERSION     NAMESPACE
bar             1               Thu May 30 07:07:43 2019        DEPLOYED        pravega-0.5.0                   0.5.0           default
deena           1               Thu May 30 06:50:41 2019        DEPLOYED        pravega-operator-0.3.2          0.3.2           default
```

Due to this PravegaCluster pods doesn't come up even though pravega installed through 'helm install' method
```
# helm install charts/pravega --name bar --set zookeeperUri=pravega-zk-client:2181
NAME:   bar
LAST DEPLOYED: Thu May 30 07:07:43 2019
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1alpha1/PravegaCluster
NAME         AGE
bar-pravega  1s

# kubectl get PravegaCluster
NAME          VERSION   DESIRED VERSION   DESIRED MEMBERS   READY MEMBERS   AGE
bar-pravega                                                                 4m
```

**Comment by adrianmo** [comment]
@deenav thanks for reporting it. I've submitted a PR to update the default version to 0.4.0 in the Helm chart. However, I don't know why your Pravega cluster is not getting deployed. Can you please show the output of `kubectl get pods`, the operator logs, and the pod description/logs if there's any failing pod?

Thank you.

**Comment by deenav** [comment]
@adrianmo I have destroyed that cluster and able to reinstall with operator `0.4.0`. Pravega Cluster deployed properly  and I don't have the logs for previous state now.
