### ISSUE TITLE
Webhook service  not cleaned up on uninstall

### ISSUE THREAD

**Issue by jkhalack** [pravega/pravega-operator#207]
After uninstalling `pravega-operator`, there is an outstanding service left over in the operator namespace:

```
$kubectl get services -n pravega
NAME                        TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)   AGE
pravega-admission-webhook   ClusterIP   10.100.200.85   <none>        443/TCP   80m
```

Please, ensure that everything gets cleaned up on uninstall.

**Comment by Tristan1900** [comment]
Thanks for the report, this is dup with #203

**Comment by jkhalack** [comment]
Sorry, haven't seen that.
Will close the issue.
