### ISSUE TITLE
Not able to scale up controller POD  after setting "kubectl autoscale deployment.apps/pravega-pravega-controller --max=5 --cpu-percent=80"

### ISSUE THREAD

**Issue by vedanthh** [pravega/pravega-operator#215]
**Not able to scale up controller POD by editing "kubectl edit pravegacluster" after setting "kubectl autoscale deployment.apps/pravega-pravega-controller --max=5 --cpu-percent=80"**

**Observed that Controller POD will get created and deleted when tried to scale-up within the max value set in "kubectl autoscale" policy**

```
  pravega:
    cacheVolumeClaimTemplate:
      accessModes:
      - ReadWriteOnce
      dataSource: null
      resources:
        requests:
          storage: 30Gi
      storageClassName: standard
    controllerReplicas: 4

```
`Kubectl get po --watch`
```
pravega-pravega-controller-676bc75bfb-w9p2c   0/1       Pending   0         <invalid>
pravega-pravega-controller-676bc75bfb-w9p2c   0/1       Pending   0         <invalid>
pravega-pravega-controller-676bc75bfb-w9p2c   0/1       ContainerCreating   0         <invalid>
pravega-pravega-controller-676bc75bfb-w9p2c   0/1       Running   0         <invalid>
pravega-pravega-controller-676bc75bfb-w9p2c   0/1       Terminating   0         <invalid>
```

Environment details: PKS / K8 with medium cluster:
```
3 master: xlarge: 4 CPU, 16 GB Ram, 32 GB Disk
5 worker: 2xlarge: 8 CPU, 32 GB Ram, 64 GB Disk
Tier-1 storage is from VSAN datastore
Tier-2 storage curved on NFS Client provisioner using Isilon as backend
```
```
Pravega version : 0.5.0-2284.8c6c176
Zookeeper Operator : pravega/zookeeper-operator:0.2.2
Pravega Operator: pravega/pravega-operator:0.3.2
```

`kubectl get hpa`
```
NAME                         REFERENCE                               TARGETS   MINPODS   MAXPODS   REPLICAS   AGE
pravega-pravega-controller   Deployment/pravega-pravega-controller   1%/80%    1         5         4          1h
[root@manager1 ~]#


NAME                                                             REFERENCE                               TARGETS   MINPODS   MAXPODS   REPLICAS   AGE
horizontalpodautoscaler.autoscaling/pravega-pravega-controller   Deployment/pravega-pravega-controller   1%/80%    1         5         4          1h
```
Events in `kubectle describe pod`
```
Events:
  Type    Reason     Age        From                                           Message
  ----    ------     ----       ----                                           -------
  Normal  Scheduled  <invalid>  default-scheduler                              Successfully assigned default/pravega-pravega-controller-676bc75bfb-smqp4 to 4bf9a49e-dc94-4a01-99c7-06300c575ac1
  Normal  Pulled     <invalid>  kubelet, 4bf9a49e-dc94-4a01-99c7-06300c575ac1  Container image "devops-repo.isus.emc.com:8116/nautilus/pravega:0.5.0-2284.8c6c176" already present on machine
  Normal  Created    <invalid>  kubelet, 4bf9a49e-dc94-4a01-99c7-06300c575ac1  Created container
  Normal  Started    <invalid>  kubelet, 4bf9a49e-dc94-4a01-99c7-06300c575ac1  Started container
  Normal  Killing    <invalid>  kubelet, 4bf9a49e-dc94-4a01-99c7-06300c575ac1  Killing container with id docker://pravega-controller:Need to kill Pod
```

**Note: Once i delete `autoscale` policy able to scale up `controller` using `kubectl edit pravegacluster`**

```
# kubectl delete horizontalpodautoscaler.autoscaling/pravega-pravega-controller
horizontalpodautoscaler.autoscaling "pravega-pravega-controller" deleted
```

**Comment by pbelgundi** [comment]
Not able to understand what is the issue here ?

Based on above description, when horizontal pod auto-scaler is enabled (using `kubectl autoscale`), if we set the number of controller replicas using `kubectl edit pravegacluster`, that does not seem to take effect.
However, the number of replicas set using `kubectl edit pravegacluster` takes effect when auto-scaler is deleted.

This is obvious and expected behavior. 

We add an auto-scaler to a deployment so we can dynamically increase/decrease the number of replicas based on a certain metric ( in this case cpu-utilization ). Hence number of replicas set via manifest does not matter, as k8s would continuously monitor CPU utilization and add/remove replicas based on the current utilization and target value. 
With auto-scale enabled, number of replicas is decided by auto-scaler configuration and load and not by the value in the manifest.

**Comment by sumit-bm** [comment]
@pbelgundi Is there any pointer proving the above hypothesis you made? How this new feature of K8 is just getting closed w/o much explanation or exploration? As per the understanding, auto scale and manual scale could work together as well.

**Comment by pbelgundi** [comment]
Please refer k8s documentation for kubernetes behaviour when autoscale is enabled:
https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/
https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/

**Comment by fpj** [comment]
As per our conversation offline, mixing auto-scaling and manual scaling is not a scenario that we are contemplating for the `0.3.3` release of the operator. Let's investigate further our options and consider such scenarios in a future release.

**Comment by pbelgundi** [comment]
@sumit-bm and @vedanthh could you please update this issue with the following:

1. The pravega/pravega-operator use-case ( scenario) you are trying to test.
2. Steps to reproduce (For eg: It is not clear what you tried changing with `kubectl edit pravegacluster`... my guess is this was number of controller replicas... but it would help to state that clearly )
3. Expected outcome.
4. Actual outcome.
