### ISSUE TITLE
`kubectl rollout` commands are not working with Pravega Rolling upgrade

### ISSUE THREAD

**Issue by deenav** [pravega/pravega-operator#216]
With Pravega-Operator:0.4.0, I am trying to run few `kubectl Rollout` commands like `status` and `history` after performing Pravega upgrade from `0.5.0-2269.6f8a820` to `0.5.0-2284.8c6c176` using `kubectl edit pravegacluster` but looks like these commands are not working at the `PravegaCluster` level. 
```
# kubectl rollout status pravegacluster
error: no kind "PravegaClusterList" is registered for version "pravega.pravega.io/v1alpha1" in scheme "k8s.io/kubernetes/pkg/kubectl/scheme/scheme.go:28"
# kubectl rollout history pravegacluster
error: no kind "PravegaClusterList" is registered for version "pravega.pravega.io/v1alpha1" in scheme "k8s.io/kubernetes/pkg/kubectl/scheme/scheme.go:28"
```

Instead if I run these commands for Segmentstore Statefulset and Controller deployments then it is showing following results.
```
[root@master ~]# kubectl rollout status statefulset.apps/pravega-pravega-segmentstore
statefulset rolling update complete 3 pods at revision pravega-pravega-segmentstore-5db65cb698...
[root@master ~]# kubectl rollout history statefulset.apps/pravega-pravega-segmentstore
statefulset.apps/pravega-pravega-segmentstore
REVISION
0
0
1
2

[root@master ~]# kubectl rollout status deployment.apps/pravega-pravega-controller
deployment "pravega-pravega-controller" successfully rolled out
[root@master ~]# kubectl rollout status statefulset.apps/pravega-bookie
error: rollout status is only available for RollingUpdate strategy type
```

**Comment by pbelgundi** [comment]
The command `kubectl rollout status pravegacluster` is incorrect as it omits the pravega object name

`kubectl rollout` is not expected to work with pravegacluster objects as it is supported only for StatefulSets, DeploymentSets and DaemonSets. 
K8s documentation : https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#rollout

We'll see if there is a way to get this to work with PravegaCluster and what it takes to make that happen.

**Comment by pbelgundi** [comment]
Changing priority to P3 as it is still possible to get status of upgrade by querying individual components.

**Comment by EronWright** [comment]
On one hand, we should resist exposing the internals of the cluster to the user (e.g. the use of statefulsets).   This would be a downside of the suggested workaround.

On the other hand, the `rollout` command might not be extensible to custom resource types.    I doo see that the kubectl code was made more generic in recent versions.  @deenav what version of kubectl are you using?

Considering that there's numerous scalable elements of a Pravega cluster (e.g. BK, SS, controller), the command doesn't seem like a good fit.   See #85 for more info on that subject.  I would suggest closing this as 'won't fix'.

**Comment by deenav** [comment]
@EronWright I am using Kubectl version "v1.13.5"

**Comment by pbelgundi** [comment]
Information provided by `kubectl rollout status` will now be provided in the output of `kubectl describe pravegacluster pravega`. Please see upgrade documentation for details.
Fixed by PR: https://github.com/pravega/pravega-operator/pull/254
