### ISSUE TITLE
During Pravega Upgrade process existing pravega pod logs gets deleted

### ISSUE THREAD

**Issue by deenav** [pravega/pravega-operator#217]
### Description
From version 0.4.0 onwards, Pravega Operator supports rolling upgrade for Pravega cluster. But during upgrade, it is observed that old (before upgrade) logs of pravega pods are not available upon upgrade completion.  This behavior is due to the pods gets deleted and re-created as part of rolling upgrade.

So, customers will loose the existing Pravega logs when they are planning to upgrade to new version. 

### Suggestions for an improvement
Pravega should inform (Interactive warning message to get the confirmation for proceeding upgrade) the users to take the logs backup before proceeding with upgrade. 
Otherwise we should at least document this limitation in upgrade section so that customers will be aware of it.

**Comment by Tristan1900** [comment]
Thanks for the report. The rolling upgrade process is using two different replicasets, so the upgraded pod is actually a new pod and it is expected to have this behavior. 
Will add README for this.

**Comment by Tristan1900** [comment]
Closing this since the doc has been added already.
