### ISSUE TITLE
Pravega upgrade from `0.5.0` to `0.6.0` fails with Pravega-operator:0.4.0 

### ISSUE THREAD

**Issue by deenav** [pravega/pravega-operator#218]
### Description

**Pravega upgrade from `0.5.0` to `0.6.0` version fails with pravega-operator:0.4.0.**

After deploying Pravega `0.5.0-2269.6f8a820` with operator:0.4.0, I tried upgrading Pravega to `0.6.0-2300.f7ef248` version using `kubectl edit pravegacluster`.  Upgrade failed with `unsupported Pravega cluster version 0.6.0-2300.f7ef248` error.

```
[root@master ~]# kubectl get pravegacluster
NAME      VERSION              DESIRED VERSION   DESIRED MEMBERS   READY MEMBERS   AGE
pravega   0.5.0-2269.6f8a820                     9                 9               5d
[root@master ~]# kubectl edit pravegacluster
error: pravegaclusters.pravega.pravega.io "pravega" could not be patched: Internal error occurred: admission webhook "mutatepravegaclusters.example.com" denied the request: unsupported Pravega cluster version 0.6.0-2300.f7ef248
You can run `kubectl replace -f /tmp/kubectl-edit-a92yy.yaml` to try this update again.
[root@master ~]#
```

### Suggestions for an improvement

Pravega `0.6.0` version needs to be added in to the Admission webhook supported version key value pair. https://github.com/pravega/pravega-operator/blob/d53e8d5305a750efb49d4175be28618fb83fdb14/pkg/webhook/webhook.go#L36

**Comment by pbelgundi** [comment]
In the code I do not see any entries supporting upgrades from one major version of Pravega to the next. Going by this matrix, upgrade from 0.4.0 to 0.5.0 also would not be allowed.
Working on figuring out why that is the case and how to make this more flexible.
