### ISSUE TITLE
Support passing of java options to bookkeeper from .yaml file

### ISSUE THREAD

**Issue by pbelgundi** [pravega/pravega-operator#226]
### Description
Currently values specified under "Options" in 'bookkeeper spec' in .yaml file for Pravega, are considered as bookkeeper server configuration options and there is no way to pass java options to the bookie process from a .yaml file.

### Importance
It is important to support this as we may need to tweak working of bookkeeper in some environments using java options, passed to the bookie process using the -D flag.

### Location
https://github.com/pravega/pravega-operator/blob/master/pkg/controller/pravega/bookie.go#L253

Pravega options:
Such options can be passed to the pravega image using "options" field in the spec. 
https://github.com/pravega/pravega-operator/blob/master/pkg/controller/pravega/pravega_controller.go#L164

**Comment by Tristan1900** [comment]
Can I ask a question? What is the difference between bookkeeper server configuration options and java options(`-D`), I'm working on a related PR today and they look the same thing to me. Thanks! @pbelgundi

**Comment by pbelgundi** [comment]
@Tristan1900 If you follow code links provided above, you will notice that "options" provided under "bookkeeper spec" are added to bookkeeper config map with the prefix "BK_". These are then added to "conf/bk_server.conf" file on the bookkeeper pod, as bookkeeper server options.
On the other hand, options provided to pravegaspec are prefixed with "-D" and provided as command line JVM options to controller and segment store processes.

As such, whatever K:V pairs are added under bookkeeper options, are not passed as JVM options to the bookkeeper process.

**Comment by Tristan1900** [comment]
@pbelgundi Thanks for the explanation. What is exactly you want to pass using `-D`? 

From what I see, the `-D` is for java property and it can be passed using `-D` along with other non-standard(-X) and advanced(-XX) JVM options in the command line, but also can be passed using a config file, which is what bookkeeper is doing(using `conf/bk_server.conf`). Check [here](https://github.com/apache/bookkeeper/blob/master/bin/bookkeeper#L159). If you just want to pass java property to bookie similar to Pravega controller and segmentstore, then I think that has already been done. If you want to pass something else except java property using `-D`, please clarify what that is as I don't see such case right now.

The only missing part is to add the ability for users to pass non-standard(-X) and advanced(-XX) JVM options, which is not exactly what this issue describes.

**Comment by pbelgundi** [comment]
@Tristan1900 Users may want to pass JVM options of any of these kinds: -D, -XX, or -X, to the bookkeeper server process.
Currently operator does not support passing of any of these from the manifest. 
There are some hard-coded values for java options and the same are always passed to the server by operator.
To confirm this, please try adding -D or -X properties under "options" in 'bookkeeper spec' and check if these get passed to the server process as in case of controller/segment store processes.

IMO, it would be good to have 2 separate fields "options" and "jvm_options" in the  bookkeeper spec. The first set of values would be bookkeeper server configuration properties and the second set can be JVM options. Here we also need to check if user wishes to override any existing properties already being set by the operator.

**Comment by pbelgundi** [comment]
Currently, the intent of "options" field in "Bookkeeper Spec" is to provide bookkeeper server options as specified [here](https://github.com/pravega/pravega-operator/blob/master/doc/bookkeeper-options.md).
These get added to bk_server.conf file on the bookie pod and not passed as JVM options to the server.

**Comment by pbelgundi** [comment]
> which is what bookkeeper is doing(using `conf/bk_server.conf`).

Whatever is added to 'options' under bookkeeper spec, I do not see it getting added as -D flag to the bookkeeper server process. It is added to bk_server.conf which is passed as parameter to the bookkeeper Main, using --conf argument.

**Comment by pbelgundi** [comment]
Here are the default JVM options passed to bookkeeper server process :
```
-Djava.net.preferIPv4Stack=true -Xms1g -XX:MaxDirectMemorySize=1g -XX:+ExitOnOutOfMemoryError -XX:+CrashOnOutOfMemoryError -XX:+HeapDumpOnOutOfMemoryError -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=2 -XX:+UseG1GC -XX:MaxGCPauseMillis=10 -XX:+ParallelRefProcEnabled -XX:+AggressiveOpts -XX:+DoEscapeAnalysis -XX:ParallelGCThreads=32 -XX:ConcGCThreads=32 -XX:G1NewSizePercent=50 -XX:+DisableExplicitGC -XX:-ResizePLAB -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCApplicationStoppedTime -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=5 -XX:GCLogFileSize=64m -Xloggc:/opt/bookkeeper/logs/gc_%p.log -Dio.netty.leakDetectionLevel=disabled -Dio.netty.recycler.maxCapacity.default=1000 -Dio.netty.recycler.linkCapacity=1024 -Dlog4j.configuration=log4j.properties -Dbookkeeper.root.logger=INFO,CONSOLE -Dbookkeeper.log.dir=/opt/bookkeeper/logs -Dbookkeeper.log.file=bookkeeper-server.log -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.local.only=false org.apache.bookkeeper.server.Main --conf /opt/bookkeeper/conf/bk_server.conf
```
As you can see there are several options with the -D flag that are used to tweak the logging, netty behaviour etc....

**Comment by Tristan1900** [comment]
@pbelgundi Thanks. I see your point.
