### ISSUE TITLE
Segmentstore cache should use local disk if PVC is not specified

### ISSUE THREAD

**Issue by Tristan1900** [pravega/pravega-operator#228]
### Description
Right now the Segmentstore cache is using a persistent volume to store data. If the pvc template is not specified, the operator will set a default pvc template. However, according to this [line](https://github.com/pravega/pravega-operator/blob/master/pkg/apis/pravega/v1alpha1/pravega.go#L91), a `emptyDir` should be used if a template is not provided.

Also, local disk tends to have better latency performance than remote disk, one might want to just use `emptyDir` in some situations. 

### Importance
Potential blocker to various issues in Pravega

### Location
Segmentstore deployment code and api code.

### Suggestions for an improvement
If the pvc template is not provided in pravega manifest, use an `emptyDir` as the segmentstore cache volume.

**Comment by pbelgundi** [comment]
See related issue: https://github.com/pravega/pravega/issues/4011

**Comment by Tristan1900** [comment]
Not needed anymore.
