### ISSUE TITLE
Ensure all ledgers are replicated in Bookie when upgrading. 

### ISSUE THREAD

**Issue by Tristan1900** [pravega/pravega-operator#235]
### Description

The current upgrade process is to start to upgrade a new bookie pod once the previous bookie pod is ready. However, the readiness probe is only to write/read entries from the local bookie, it does not guarantee that the ledgers are all replicated. We should wait for the ledgers to be replicated and then continue to upgrade the next bookie pod.

### Importance

Could cause DUDL scenario. 

### Location

[here](https://github.com/pravega/pravega-operator/blob/master/pkg/controller/pravegacluster/upgrade.go#L268)

### Suggestions for an improvement

Leverage this command `bin/bookkeeper shell listunderreplicated` to make sure ledgers are all replicated.

**Comment by fpj** [comment]
Good suggestion, @Tristan1900 :

> Leverage this command bin/bookkeeper shell listunderreplicated to make sure ledgers are all replicated.

**Comment by Tristan1900** [comment]
@fpj It would be great if you could shed some light on this issue. Thanks!

I have thought about implementation and it might require the Bookkeeper upgrade logic to change. The current upgrade relies on the readiness probe and we can't just add `bin/bookkeeper shell listunderreplicated` to the readiness probe, that will make the entire cluster not ready if the return of that function is not zero. So before making any changes, I would like to make sure what is the problem we are facing. 

Take an example of 3:3:2 Ensemble3(E3), QuorumWrite3(Qw3), QuorumAck2(Qa2), B0,B1,B2. If B0 is upgrading, B1 and B2 will Ack and the write to B0 is fails, now the BK client will find a replacement B3 for B0. After B0 is upgraded and ready, we immediately continue to upgrade the next pod B1. The next entry is written to B1,B2,B3, and write to B1 fails. So the BK client will find another replacement for B1, the ensemble will become B2,B3,B4 or B0,B2,B3 since B0 is up from upgrade before. 

Given the above example, I don't see why there is an under replicated scenario. I think the under replicated scenario only happens when a Bookie is not coming back, so the entries it stores will be under replicated, and that will be handled by Autorecovery or maybe pod just restarted by K8s.

Thanks in advance!

**Comment by pbelgundi** [comment]
@Tristan1900, lets work out all feasible solutions for this problem and then try to pick the best one.

**Comment by pbelgundi** [comment]
@Tristan1900, Assuming bookies are upgraded one at a time, I agree that there does not seem to be any need to check for `underreplicated bookies`.
However, we should disable `autorecovery` before upgrade and enable it again once the upgrade is complete to avoid unnecessary re-replication.
As per Bookkeeper documentation:
```
Disabling AutoRecovery ensures that bookies’ data isn’t unnecessarily rereplicated when the bookie is only taken down for a short period of time, for example when the bookie is being updated or the configuration if being changed.
```

**Comment by pbelgundi** [comment]
Having said that, if the bookie being updated fails to come up with the new version, disabling auto-recovery could cause more harm than good.

**Comment by fpj** [comment]
Say we have a ledger _L_ replicating entries across three bookies: _B1 B2 B3_. For the sake of example, say that quorum size is 2. Let's use _L(Bi)_ to denote the data of ledger _L_ in bookie _Bi_.

 In the case a bookie crashes, auto-replication in BookKeeper will ensure that the degree of replication is established. For example, if _B1_ crashes, then it needs to replicate _L(B1)_ in another bookie, say _B4_. The mechanism uses entries from _B2_ and _B3_ to reconstruct _L(B1)_.

Now consider the following situation:

- We upgrade _B1_, which makes it wipe out its data
- _B1_ is up again, so the upgrade of _B2_ restarts, but _L(B1)_ is not necessarily written to a new bookie.
- As the degree of replication is 2 (quorum size), there are entries that are replicated only in _B1_ and _B2_.

Consequently, wiping out the data of _B2_ due to the upgrade before ensuring that _L(B1)_ is replicated elsewhere induces a data loss.

**Comment by Tristan1900** [comment]
I see, thanks @fpj !
So currently when upgrading bookies, we do not wipe out bookie data(we definitely could do that by manually delete the PVC if wiping out data is necessary). The data is in persistent volume and the pod is only temporarily brought down and restarted and connected back to the PVC. So that bookie only loses the incoming data during its upgrading, it does not lose data it already has. 
@pbelgundi Please correct me if I'm wrong, thanks!

**Comment by pbelgundi** [comment]
Yes, since data is stored in a persistent volume, it is not lost post upgrade. To confirm this I manually created a test file on the ledger volume on bookie-0 and then post upgrade could still see that file.

**Comment by fpj** [comment]
If the data of a bookie is preserved during upgrade and auto-replication is disabled, then we don't really have under-replicated data. The only danger is that a bookie going through upgrade never comes back, but in that case, we won't start an upgrade with another bookie, which seems safe.

The question is what happens to the upgrade overall in the case at least one bookie never comes back.

**Comment by pbelgundi** [comment]
@fpj, Data on a bookie is preserved during upgrade.
"Autorecovery" is enabled by default and is currently not "disabled" during upgrade. 
IMO that could lead to some eventual "over-replication", which should be fine.

If a bookie node being upgraded never comes back, this would stall the upgrade process and put the cluster in an Error state. On every pass of the reconcile loop, operator would try to bring back the Failed bookie pod. Recovery process is a TBD.

**Comment by pbelgundi** [comment]
There should not be any issue with temporary under-replication of ledgers during upgrades as long as upgrade is not stuck forever. After a certain time interval, post start of upgrade either upgrade completes (after this auto-recovery will make sure ledgers are fully replicated) or upgrade will fail and rollback will be triggered. On completion of rollback again auto-recovery would make sure underreplicated ledgers, if any are dealt with.

**Comment by pbelgundi** [comment]
Though Bookkeeper auto-recovery is enabled by operator, its execution frequency, trigger and efficiency is governed by the some configurable properties which can be tuned to decide how long we want to tolerate data loss before kick starting the recovery process.
Note that the recovery process has its own execution overhead, so we may want to strike a balance between data loss and performance overhead the recovery process would add.
This could also vary from usecase to usecase and hence should be configurable.

For details of Auto Recovery process see: https://bookkeeper.apache.org/docs/4.7.3/admin/autorecovery/#autorecovery

Some Configuration Properties that impact auto-recovery:
1. auditorPeriodicBookieCheckInterval - The time interval between auditor bookie checks, in seconds. The auditor bookie check, checks ledger metadata to see which bookies should contain entries for each ledger. If a bookie that should contain entries is unavailable, then the ledger containing that entry is marked for recovery. Defaults to once per day.
2. auditorPeriodicCheckInterval - The time interval, in seconds, at which the auditor will check all ledgers in the cluster. By default this runs once a week. Defaults to once per week.
3. lostBookieRecoveryDelay - How long to wait, in seconds, before starting autorecovery of a lost bookie. Defaults to 0.
4. underreplicatedLedgerRecoveryGracePeriod - The grace period (in seconds) for underreplicated ledgers recovery. If ledger is marked underreplicated for more than this period then it will be reported by placementPolicyCheck in Auditor. Setting this to 0 will disable this check. Default is 0.

**Comment by pbelgundi** [comment]
Moved to Bookkeeper-Operator: https://github.com/pravega/bookkeeper-operator/issues/38
