### ISSUE TITLE
Generate admin password at install time

### ISSUE THREAD

**Issue by sachin-j-joshi** [pravega/pravega-operator#239]
### Description

Currently, the pravega controller is initialized with a baked in password file for its default auth handler.  It has one hard coded user "admin" with known password, with full rights to the entire pravega operation set.

### Importance

must-have

### Location

Pravega operator

### Suggestions for an improvement

Generate this username and password pair at install time, inject the resulting password file into the pravega controller's container.  And the credentials themselves in the segment stores' pods.

This will require the use of a tool based on https://github.com/pravega/pravega/blob/master/controller/src/test/java/io/pravega/controller/auth/PasswordFileCreatorTool.java that we can invoke at install time.

Additionally, this will involve a change in the PravegaCluster CRD and the pravega-operator such that one can supply a secret name or/and volume containing the password file, which the operator would mount into the pravega controller pod.

Requires a design discussion.

**Comment by EronWright** [comment]
I see two separable elements here:
1. Support for a `Secret` containing the password file, which would be mounted into the requisite pods by the operator.
2. A documented procedure for generating such a `Secret`.    I imagine the procedure to resemble the following:
a. `pravega-cli passwordfile add -f ./passwd -u admin -p mypassword`
b. `kubectl create secret generic pravega-passwd --from-file=./passwd`
c.  configure `PravegaCluster` to use `pravega-passwd` as the password file

**Comment by pbelgundi** [comment]
Created issue for PasswordCreationTool: https://github.com/pravega/pravega-tools/issues/43
