### ISSUE TITLE
Pass jvm options to the deployment

### ISSUE THREAD

**Issue by Tristan1900** [pravega/pravega-operator#246]
### Description

It is good to have a way to pass jvm options to Pravega deployment so we can tune the system.

### Importance

should-have

### Location

In controller, segmentstore and bookie

### Suggestions for an improvement

Add a field in the manifest.

**Comment by pbelgundi** [comment]
@Tristan1900 how is this different from #226

**Comment by pbelgundi** [comment]
Duplicate for #226
