### ISSUE TITLE
Prohibit editing pravega version to any version other than previous version during rollback 

### ISSUE THREAD

**Issue by Richa-Srivastava** [pravega/pravega-operator#299]
Once the Upgrade fails, due to any reason, to trigger rollback, we should prohibit editing PravegaCluster `version` detail to any other version and should restrict to only provide previous version.

Currently we can provide any other version and its not mandatory to give previous version, which is causing cluster to remain in same state as no `rollback` gets triggered.
Pravega config details:
```
bookkeeper:0.6.0-2408.7312399
pravega:0.6.0-2408.7312399
pravega/pravega-operator:0.4.2
pravega/zookeeper:0.2.4
pravega/zookeeper-operator:0.2.4
```

**Comment by pbelgundi** [comment]
Fixed by : https://github.com/pravega/pravega-operator/pull/310
