### ISSUE TITLE
Add an 'admission hook' to sanitize values prior to upgrade

### ISSUE THREAD

**Issue by jadnhm** [pravega/pravega-operator#306]
### Description

An admission hook will be required which can check values prior to an upgrade. 

In this case the container count was changed from 24 to 48 (which is apparently not allowed during an upgrade) and the upgrade still runs but some metrics are no longer being reported.

### Importance

must-have/should-have

**Comment by pbelgundi** [comment]
@jadnhm  could you please provide some more details on the values you tried to edit and the expected vs. actual outcome.

**Comment by pbelgundi** [comment]
A validation webhook is already present. 
Changing segment container count is not allowed in Pravega once the cluster is deployed:
http://pravega.io/docs/v0.5.0/segment-containers/#segment-containers
This is by design.
