### ISSUE TITLE
Allow Deploying Pravega Operator Chart In TestMode

### ISSUE THREAD

**Issue by jdmaguire** [pravega/pravega-operator#324]
### Description

Some non-production features are behind TestMode. It would be nice to be able to set that in the values when installing the chart.

### Importance

For running small BK instances in say minikube or small deploys

### Location

Charts

### Suggestions for an improvement

Allow setting TestMode through a values flag.

**Comment by pbelgundi** [comment]
In "test-mode", pravega-operator allows deployment of pravega with a single bookie instance.
However, currently when deployed on a K8s cluster the operator  cannot be run in "test mode" and as such in a demo/ basic production environment it is not possible to run pravega with single bookkeeper instance.
This feature may be needed when running pravega on minikube or on clusters with limited resources.

**Comment by anishakj** [comment]
We can enable the test mode, by specifying `test` flag,  Tested by making the below  changes in `yaml` file, able to deploy 2 bk instances.
```containers:
  - name: pravega-operator
    image: devops-repo.isus.emc.com:8116/nautilus/pravega-operator:0.4.3-rc1
    ports:
    - containerPort: 60000
      name: metrics
    command:
    - pravega-operator
    imagePullPolicy: Always
    args: [-test]
```

**Comment by pbelgundi** [comment]
Above changes work when using "operator.yaml". But charts may need some changes to get this work with charts.

**Comment by pbelgundi** [comment]
@anishakj it would help to add documentation to the Readme or the manual installation doc, explaining how operator can be run in test mode.

**Comment by anishakj** [comment]
> Above changes work when using "operator.yaml". But charts may need some changes to get this work with charts.

We can make the similar changes in `charts/pravega-operator/templates/operator.yaml` and it will work with charts as well
