### ISSUE TITLE
Example manifest is not updated with latest Bookkeeper changes

### ISSUE THREAD

**Issue by RaulGracia** [pravega/pravega-operator#346]
### Description
The manifest in `examples` directory are not up to date. They do not reflect the changes of splitting Pravega and Bookkeeper.

### Importance
Should-have.

### Location
Examples directory.

### Suggestions for an improvement
Fix the example manifest.

**Comment by jdmaguire** [comment]
You beat me to this Raul! I was looking at the cr-detailed.yaml example for something unrelated and noticed this.
