### ISSUE TITLE
Travis build is not deleting clusters in case of before_script failure

### ISSUE THREAD

**Issue by anishakj** [pravega/pravega-operator#356]
### Description

In travis build, if any steps of before_script is failing , cluster is not getting deleted

### Importance

Must have

### Location

.travis.yml

### Suggestions for an improvement

Combine before_script and script section together

**Comment by pbelgundi** [comment]
@anishakj Could you please explain the impact of this issue? Does this often cause travis build failures?

**Comment by anishakj** [comment]
Closing  this issue, as it is not valid after we moved to CNCF clusters.
