### ISSUE TITLE
Upgrade from Pravega version<0.7 to Pravega Version>=0.7 with external access enabled is failing

### ISSUE THREAD

**Issue by Prabhaker24** [pravega/pravega-operator#358]
### Description
Because of the changes for fixing of #312 we have modified the name of the segment store for versions above 0.7 but have not changed the service name and the script that runs as part of the creation of segment store needs the new service name.
 
### Importance
Must have

### Location
upgrade.go
 
### Suggestions for an improvement
In the upgrade.go while deleting the segment store pod for version <0.7 remove the service as well

**Comment by jkhalack** [comment]
Please, take into account that upgrade from 0.7.0 pravega that was deployed with 0.4.x releases of pravega-operator is failing too (the previous versions of pravega-operator used uniform naming for all versions of pravega).

**Comment by Prabhaker24** [comment]
this is fixed this pr https://github.com/pravega/pravega-operator/pull/368
