### ISSUE TITLE
Error event not generated for second time if the pravega upgrade fails

### ISSUE THREAD

**Issue by SrishT** [pravega/pravega-operator#361]
### Description
If an upgrade from version X to version Y fails, an event is generated by the pravegacluster for this Failed Upgrade. After successfully rolling back to version X from here, if the next upgrade from version X to version Z fails again, no event is generated for this second failed upgrade.

### Importance
must-have

**Comment by pbelgundi** [comment]
This behavior is seen because of Event Aggregation done by Kubernetes in case when the same event is generated multiple times within one hour
