### ISSUE TITLE
Pravega Cluster setup script updation

### ISSUE THREAD

**Issue by SrishT** [pravega/pravega-operator#373]
### Description
The setup script needs to be updated to install the cert-manager as well from pravega operator 0.5.0-rc1 onwards.

### Importance
should have

### Location
setup/pravegacluster.sh

### Suggestions for an improvement
The script should seamlessly handle deployment of all dependencies in the required order.

**Comment by pbelgundi** [comment]
`cert-manager` setup is a pre-requisite and should **not** be done by the setup script, since users may also choose to use different certificate management solutions.
