### ISSUE TITLE
Move User documentation in docs folder to Operator github wiki

### ISSUE THREAD

**Issue by pbelgundi** [pravega/pravega-operator#389]
### Description
wiki offers better rendering and ease of access for documents.
Also documents added to wiki are not tied to a specific release/branch or codebase.

### Importance
must-have

### Location
https://github.com/pravega/pravega-operator/tree/master/doc

### Suggestions for an improvement
Move User documentation under : https://github.com/pravega/pravega-operator/tree/master/doc to a suitable location under https://github.com/pravega/pravega-operator/wiki

**Comment by ravisharda** [comment]
@fpj my understanding based on some of the comments from old PRs is that the general rule that we follow in Pravega is that developer-oriented documentation (like design docs, contribution guidelines, etc.) goes in the Wiki and user-oriented documentation goes in the source-code.

Does that rule also apply to operators? 

I think it should make sense to do that, for these two reasons:
1. When you navigate to a particular branch, you can see the user documentation that applies to the same branch. 
2. We could publish those docs to pravega.io version-wise (like we do for Pravega docs located in https://github.com/pravega/pravega/tree/master/documentation/src. 

cc @pbelgundi @Prabhaker24

**Comment by pbelgundi** [comment]
Thanks for bringing this up @ravisharda 
I wasn't aware of this convention. 
It does make sense to continue to have user documentation in docs folder for reasons mentioned above, though I do think that documentation is more easily located on wikis rather than docs folder.
We will continue to have user documentation in docs folder instead of wiki.

**Comment by fpj** [comment]
As @ravisharda mentions, the user documentation is supposed to be made available on pravega.io for each released version. We don't expect users to search and locate them in a docs folder in the source repository.
