### ISSUE TITLE
Add bkLedgersPath parameter to Pravega Helm chart

### ISSUE THREAD

**Issue by RaulGracia** [pravega/pravega-operator#393]
### Description
Currently, deploying Bookkeeper and Pravega via Helm has one usability impediment; the configuration of _Bookkeeper ledgers path_. The problem is that none of the Helm Charts allow us to fully configure the Zookeeper location where the metadata of ledgers is going to be set.

At the moment, the only known way to make this to work is to change the "pravegaCluster" value in the `values.yaml` file of Bookkeeper chart to make it match what Pravega expects later on. But, as one can infer, this is problematic, specially when trying to educate new users on how to deploy a demo Pravega cluster.

While the long term goal may be to have full flexibility in all the parameter settings of Bookkeeper and Pravega via Helm, one immediate fix to this problem would be to extend the Pravega Helm Chart to be able to set the `bkLedgersPath` parameter, which is what the Segment Store uses to lookup for Bookkeeper metadata. With this, we could just execute the default deployment command with Helm for Bookkeeper, and then instruct Pravega where to look for the metadata of Bookkeeper ledgers like this:
```
helm install pravega-operator/charts/pravega --name pravega --set zookeeperUri=zookeeper-zookeeper-client:2181 --set bookkeeperUri="bookkeeper-pravega-bk-bookie-headless.default.svc.cluster.local:3181" --set pravega.longtermStorage=pravega-tier2 --set bkLedgersPath="/bookkeeper/pravega/legers"
```

Concretely, The new parameter to add related to this issue would be:
`--set bkLedgersPath="/bookkeeper/pravega/legers"`

This would make the installation of Pravega and Bookkeeper in Kubernetes much easier, following a natural flow. I think this will be appreciated for new users trying to deploy Pravega in Kubernetes.

### Importance

Should have.

### Location

Pravega Helm Chart.

### Suggestions for an improvement

Add the possibility to set `bkLedgersPath` via Pravega Helm Chart.

**Comment by SrishT** [comment]
Fixed with PR https://github.com/pravega/pravega-operator/pull/397
