### ISSUE TITLE
Segment store resource structure

### ISSUE THREAD

**Issue by spiegela** [pravega/pravega-operator#4]
There are a few open questions regarding the proper design for the segment store resources:

- [x] Does the segment store require a persistent volume, or should the local disk be considered ephemeral?
- [x] Should the Bookkeeper be included within the segment store pod? If these are always expected to scale in concert, then it would make sense to keep them together.
- [x] Segment stores find the bookkeeper instances via Zookeeper. Does each segment store write directly to the associated Bookee?

**Comment by adrianmo** [comment]
Outdated issue. All questions have been handled in separated issues and implemented.
