### ISSUE TITLE
Don't use deprecated 'XX:MaxRAMFraction' JVM option 

### ISSUE THREAD

**Issue by medvedevigorek** [pravega/pravega-operator#461]
### Description

Since Java 10 `XX:MaxRAMFraction` option is deprecated and will be removed in future version of JVM. 

For more details, see https://bugs.openjdk.java.net/browse/JDK-8186315

### Importance

should-have

### Location

This is currently used in the default config maps for Controller and SegmentStore 

### Suggestions for an improvement

There are two options to address it: 
(a) Replace deprecated option with `XX:MaxRAMPercentage'
(b) Remove it from the list of default JVM options and let it be set via charts

**Comment by anishakj** [comment]
Fixed by PR https://github.com/pravega/pravega-operator/pull/467
