### ISSUE TITLE
Simplifying Reconcile Logic To check for updates in each specific component 

### ISSUE THREAD

**Issue by Prabhaker24** [pravega/pravega-operator#463]
### Description
In p-operator we're checking very specific things in the reconcile loop, instead of checking for updates to each component and that is complicating the flow of code way too much.

### Importance
should-have,

### Location
pravegacluster_controller.go

### Suggestions for an improvement
we can follow the way it's done for zk operator. Link to it is https://github.com/pravega/zookeeper-operator/blob/master/pkg/controller/zookeepercluster/zookeepercluster_controller.go#L150

**Comment by anishakj** [comment]
Fixed by PR https://github.com/pravega/pravega-operator/pull/456
