### ISSUE TITLE
Inconsistencies with the webhook cert name can lead to issues accessing it

### ISSUE THREAD

**Issue by sarlaccpit** [pravega/pravega-operator#470]
### Description

Inconsitency between the two paths where the webhook cert is generated or provided can cause SSL isues when accessing the webhook:

```
 Internal error occurred: failed calling webhook "pravegawebhook.pravega.io": Post https://pravega-webhook-svc.nautilus-pravega.svc:443/validate-pravega-pravega-io-v1bet
                                          a1-pravegacluster?timeout=30s: x509: certificate signed by unknown authority
```

The problem is that in the case where the cert needs to be generated ( `.Values.webhookCert.generate: true`), the `certName` field https://github.com/pravega/pravega-operator/blob/master/charts/pravega-operator/values.yaml#L37 needs to be set (despite the comment above it) and match what is used here https://github.com/pravega/pravega-operator/blob/master/charts/pravega-operator/templates/certificate.yaml#L18, else this does not work https://github.com/pravega/pravega-operator/blob/master/charts/pravega-operator/templates/webhook.yaml#L26

The reason being line 26 does not know if the cert was generated or not.  It just needs the name.

### Importance

There is a workaround, which is to ignore the comment in the value file and set the certName to match https://github.com/pravega/pravega-operator/blob/master/charts/pravega-operator/templates/certificate.yaml#L18

Therefore this is not a blocking issue but can be misleading to others who may run into the same problem.

### Location

This is a charts issue only.  See links in the description for specific locations.

### Suggestions for an improvement

The solution is to add a template helper to hide this nuance so that at the end of the day, whether the cert was generated or provided, the name is correct for what the webhookconfiguration consumes here https://github.com/pravega/pravega-operator/blob/master/charts/pravega-operator/templates/webhook.yaml#L26

**Comment by anishakj** [comment]
Fixed by PR https://github.com/pravega/pravega-operator/pull/475
