### ISSUE TITLE
Validate Pravega manifest settings before deployment.

### ISSUE THREAD

**Issue by shrids** [pravega/pravega-operator#495]
### Description

https://github.com/pravega/pravega-operator/blob/master/doc/upgrade-cluster.md#upgrade-to-pravega-07-or-above indicates that Segment store settings following rules like : 

POD_MEM_LIMIT = JVM Heap + Direct Memory
Direct Memory = pravegaservice.cache.size.max + 1GB/2GB (other uses) ; (Direct memory is less than cache.size.max)

This verification can be done before deployment by the operator instead of manually relying on the user to set it right...

With incorrect values, the Segment store faces errors of the pattern.
```
 00:39:19,662 10936089 [core-23] ERROR i.p.s.server.logs.DurableLog - DurableLog[40] Recovery FAILED.
io.pravega.segmentstore.storage.cache.CacheFullException: DirectMemoryCache full: Stored = 11788056931, Used = 11811160064, Reserved = 23068672, Allocated = 11811160064, Max = 11811160064
```
### Importance

should-have

### Location

Pre deployment validation..

### Suggestions for an improvement

Ensure Pre-condition checks like the one mentioned for SegStore are performed before deployment.

**Comment by pbelgundi** [comment]
@shrids there are multiple validation checks possible here, in addition to the ones listed above.
It would be good to list all those out as sub-tasks and prioritize.
