### ISSUE TITLE
Certificate Issue with Pravega cluster creation

### ISSUE THREAD

**Issue by dellThejas** [pravega/pravega-operator#496]
### Description

When creating a pravega cluster using existing certificates provided in the manual installation guide, an issue with certificate authorization occurs as follows:

`
Error: Internal error occurred: failed calling webhook "pravegawebhook.pravega.io": Post https://pravega-webhook-svc.default.svc:443/validate-pravega-pravega-io-v1beta1-pravegacluster?timeout=30s: x509: certificate signed by unknown authority
`
Staging section of the pravega charts is being used to access Pravega 0.9.0 from https://github.com/pravega/charts/tree/master/docs/staging

### Importance

The certificate is essential for installation of pravega cluster using the installation guide

### Location

https://github.com/pravega/pravega-operator/blob/master/doc/manual-installation.md

### Suggestions for an improvement

It is possible that the certificate issued in the https://github.com/pravega/pravega-operator/blob/master/deploy/certificate.yaml is incorrect to access these helm charts.

**Comment by anishakj** [comment]
@dellThejas Is the issue still seen?

**Comment by dellThejas** [comment]
This issue has been resolved. I did a manual installation of pravega instead of the helm operation. This fixed it.

**Comment by dellThejas** [comment]
The resolution was to update the certs before deploying the pravega-operator, and updating the config to include the pravega version that is needed.
