### ISSUE TITLE
Deprecate Script way of upgrading operator from 0.4.x to 0.5.x

### ISSUE THREAD

**Issue by Prabhaker24** [pravega/pravega-operator#498]
### Description
Deprecate Script way of upgrades of Pravega Operator from 0.4.x to 0.5.x.

### Importance
nice_to_have

### Location
Tools and Doc folder
Tools Folder Link- https://github.com/pravega/pravega-operator/tree/master/tools
Doc Folder Link- https://github.com/pravega/pravega-operator/blob/master/doc/operator-upgrade.md

### Suggestions for an improvement
1) Remove tools folder
2) Update operator upgrade documentation and Deprecate the Script way of Upgrading Operator.

**Comment by pbelgundi** [comment]
The problem with the operator upgrade documentation is that we still mention this in the documentaion :
```
Execute the script pre-upgrade.sh inside the scripts folder. This script patches the pravega-webhook-svc with the required annotations and labels. The format of the command is

./pre-upgrade.sh [PRAVEGA_OPERATOR_RELEASE_NAME][PRAVEGA_OPERATOR_NAMESPACE]
where:
```
We should be deprecating the script and mandating only helm way of doing the upgrade.
If at all we have to use the script, that should be a "backup" option not the main/default way of doing things as the document seems to suggest.
