### ISSUE TITLE
Extend functionality of Test Mode to enable privileged mode for Segment Store containers

### ISSUE THREAD

**Issue by leapsky** [pravega/pravega-operator#507]
### Description

By default, Docker containers run in unprivileged mode. However, to profile the applications, we use tracers (e.g. `perf_events`, `strace`, `ebpf programs`) that requires more sufficient privileges. We need to extend functionality of `Test Mode` to enable `privileged mode` for Segment Store containers which will grant them operating system administrative capabilities

### Importance

This functionally will allow us to use Linux tracing tools without patching Pravega Operator and make profiling more simple. 

### Location

`pkg/controller/pravega/pravega_segmentstore.go`

### Suggestions for an improvement

Enable docker container `privileged mode` in `Test Mode`

**Comment by anishakj** [comment]
Fixed by PR https://github.com/pravega/pravega-operator/pull/508
