### ISSUE TITLE
Improvements to Readme.md

### ISSUE THREAD

**Issue by pbelgundi** [pravega/pravega-operator#510]
### Description
The current `Readerme.md` has a "Table of Contents" that looks very cluttered and makes for a `very hard to read` landing document. It would be good to refactor this doc to have fewer sections and make it more easy to navigate, crisp and carry only necessary information for a "quickstart" on pravega-operator. 

Here are some suggestions on what could be part of TOC line items:
**Overview** - Explain brielfly about pravega-operator & pravega. 
Point to `pravega.io` for more details on Pravega.
_Sub-Sections:_
Prerequisites : List prerequisites.
Features: P-operator features at a glance.
Project-Status: 

**Quickstart** - Link to minikube setup, pravega-cli and pravega samples repositories here.

**Deploying Pravega** - Link to another document that details helm steps for deploying and un-deploying Pravega. Please skip mentioning manual install here as it is not a recommended way of doing things. 
_Sub-Sections:_
Configuration
Upgrades
Scaling
Troubleshooting

**Development** - Link to Development page. This page should also have link to "Contributing" guidelines.

**Community** - Link to pravega-operator and pravega slack channels

**License** - License information about this project.

### Importance
nice-to-have

### Location
https://github.com/pravega/pravega-operator/blob/master/README.md

### Suggestions for an improvement
Examples of some good landing pages:
https://github.com/GoogleCloudPlatform/airflow-operator
https://github.com/elastic/cloud-on-k8s

**Comment by anishakj** [comment]
Fixed by PR https://github.com/pravega/pravega-operator/pull/512
