### ISSUE TITLE
Pravega Helm chart does not mention provisioning of LongTermStorage  as pre-requisite.

### ISSUE THREAD

**Issue by pbelgundi** [pravega/pravega-operator#511]
### Description
Pravega Helm chart does not mention provisioning of LongTermStorage  as pre-requisite.

### Importance
must-have

### Location
https://github.com/pravega/pravega-operator/tree/master/charts/pravega#prerequisites

**Comment by anishakj** [comment]
Fixed by PR https://github.com/pravega/pravega-operator/pull/512
