### ISSUE TITLE
Allow extra volume mounts to be configured

### ISSUE THREAD

**Issue by CraneShiEMC** [pravega/pravega-operator#518]
### Description

Pravega operator should allow to specify "extra" volumes to be mounted into pravega pods, including pravega segment store pods and pravega controller pods. 

### Importance

This functionality is needed to share directories between the hosts and containers, store logs and crash dumps.

### Location

pkg/controller/pravega/pravega_controller.go
pkg/controller/pravega/pravega_segmentstore.go

**Comment by anishakj** [comment]
Fixed by PR https://github.com/pravega/pravega-operator/pull/517
