### ISSUE TITLE
Identify Operator goals and required actions

### ISSUE THREAD

**Issue by spiegela** [pravega/pravega-operator#6]
Some operator goals are fairly obvious (like deployment and scaling) we should identify which Operator goals are required for the operator to be _"minimally viable"_ for release. Also, the separation of duties between the Pravega Operator and other projects (Nautilus, Flink, etc.) should be considered.

This issue should track the goals considered for initial release. Once identified, these will be tracked as issues and added to the `0.0.1` milestone.

**Comment by EronWright** [comment]
@maddisondavid are all the above items implemented or captured as separate issues?  If so, we may close this issue.

**Comment by adrianmo** [comment]
All items have their respective issue. Closing this one.
