### ISSUE TITLE
Remove dependency to k8sutil in pravegacluster_types.go

### ISSUE THREAD

**Issue by AndreyAdnreyev** [pravega/pravega-operator#605]
### Description

The package k8sutil [was removed](https://sdk.operatorframework.io/docs/upgrading-sdk-version/v1.0.0/#removed-package-pkgk8sutil) from operator-sdk in version 1.0.0. This blocks using of PravegaCluster as a secondary resource in projects which use operator-sdk 1.0.0+.

### Importance

blocker

### Location

pkg/apis/pravega/v1beta1/pravegacluster_types.go

### Suggestions for an improvement

Opeartor SDK project suggest to  [use our own implementation](https://github.com/operator-framework/operator-sdk/pull/3475)

**Comment by anishakj** [comment]
Fixed by PR https://github.com/pravega/pravega-operator/pull/606
