### ISSUE TITLE
Add tolerations for controller and segment store pods

### ISSUE THREAD

**Issue by alfred-landrum** [pravega/pravega-operator#607]
### Description

It'd be useful to allow specifying pod tolerations for the Pravega controller and segment store pods.

### Importance

I'd like to dedicate some nodes in a cluster to run only Pravega workloads. Affinities can be used to schedule Pravega pods onto the dedicated nodes, but node taints seem the best way to prevent other non-Pravega pods from using them. To do this, I'd need to add tolerations for controller & segment store pods.

### Location

This would require adding controller & segment store pod tolerations to the Pravega cluster spec. Additionally, it'd make sense to allow the Pravega helm chart to allow specifying the tolerations as well.

**Comment by anishakj** [comment]
@alfred-landrum  Thanks for the contribution.  To make the changes in helm charts, you might need to raise a PR in https://github.com/pravega/charts
