### ISSUE TITLE
Support cluster rescaling

### ISSUE THREAD

**Issue by EronWright** [pravega/pravega-operator#62]
Do the needful to support scale changes for the various components (e.g. bookies, segment stores).

Scale down might not be supported by all components, or may require special attention.  For example, it may be necessary to drain the tier-1 storage when tearing down a given bookie.  Similar functionality may be implied by #60.

**Comment by adrianmo** [comment]
Related to #85 and #83

**Comment by adrianmo** [comment]
Closing this issue as the operator can already scale up and down all components.
