### ISSUE TITLE
Handle Go errors correctly

### ISSUE THREAD

**Issue by finiks** [pravega/pravega-operator#74]
The `ReconcilePravegaCluster()` function does not seem to handle Go errors correctly:

	deployBookie(pravegaCluster)
	if err != nil {
		return err
	}

`err` in this case is never going to be set to an error if it occurs from `deployBookie()`. We should change that first line in this scenario to `err = deployBookie(pravegaCluster)`.

**Comment by adrianmo** [comment]
Fixed in #76
