### ISSUE TITLE
Allow k8 service account to be configured for the PravegaCluster resource

### ISSUE THREAD

**Issue by sarlaccpit** [pravega/pravega-operator#79]
In some environments, the various components of the Pravega cluster may need to run under specific K8 service accounts.  Such service accounts would have different types of secrets, permissions  and/or annotations.

Two components of interest are the controller and segment stores.   Webhooks may attach different secrets to the service accounts associated with the pods running these components.   Pravega's auth plugin implementations will often require a way to inject credentials related data.

Taking as an example an implementation where the controller has a plugin that can validate an oAuth token, the controller will need some configuration injected related to the issuer.   The segment store, will need some secret/configuration in order to obtain a token when talking to the controller.

All this can be facilitated with opaque (to the operator) annotations on the K8 service accounts that get associated with the pods.     _What we need here is a way to specify which K8 service account need to be associated with the controller and the segment store._

Something along the lines of:

```
...
pravega:
   controller-service-account: foo
   segment-store-service-account: bar
...
```

The chart deploying the PravegCluster resource will be responsible for requesting foo and bar.   But the operator should responsible for settings those appropriate service account names to the correponding pods.

**Comment by adrianmo** [comment]
@sarlaccpit, yes, I think it makes a lot of sense to configure the service accounts for the Controller, Segmentstores, and Bookies. I'll work on it and submit a PR.
